[package]
name = "takumi"
version = "1.5.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Render UI component trees to images."
keywords = ["react", "image", "css", "flexbox"]
repository = "https://github.com/kane50613/takumi"
homepage = "https://takumi.kane.tw"
readme = "README.md"
rust-version = "1.91"

[dependencies]
bitflags = "2.11"
cssparser = "0.37"
paste = "1.0"
png = "0.18"
gif = "0.14"
data-url = "0.3"
color = "0.3"
thiserror = "2.0"
typed-builder = "0.23"
tiny-skia = "0.12"
svgtypes = "0.16"

[target.'cfg(target_arch = "wasm32")'.dependencies]
image-webp = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libwebp-sys = "0.14"
dashmap = "6.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.image]
default-features = false
version = "0.25"
features = ["jpeg", "png", "webp", "gif", "ico", "avif-native"]

[target.'cfg(target_arch = "wasm32")'.dependencies.bytemuck]
version = "1.25"
features = ["wasm_simd"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bytemuck]
version = "1.25"
features = ["aarch64_simd", "avx512_simd"]

[dependencies.xxhash-rust]
version = "0.8"
features = ["xxh3"]

[dependencies.phf]
version = "0.13"
features = ["macros"]

[dependencies.smallvec]
version = "1.15"
features = ["serde"]

[dependencies.parley]
version = "0.9"
default-features = false
features = ["std"]

[dependencies.skrifa]
version = "0.42"
default-features = false
features = ["std"]

[dependencies.selectors]
version = "0.38"

[dependencies.precomputed-hash]
version = "0.1"

[dependencies.rayon]
version = "1.10"
optional = true

[dependencies.wuff]
version = "0.2"
optional = true
default-features = false

[dependencies.taffy]
version = "0.10"
default-features = false
features = [
  "flexbox",
  "grid",
  "alloc",
  "calc",
  "taffy_tree",
  "strict_provenance",
  "block_layout",
  "float_layout",
]

[dependencies.serde]
version = "1"
features = ["derive", "rc"]

[target.'cfg(target_arch = "wasm32")'.dependencies.image]
default-features = false
version = "0.25"
features = ["jpeg", "png", "webp", "gif", "ico"]

[dependencies.resvg]
version = "0.47"
default-features = false
optional = true

[dependencies.roxmltree]
version = "0.21.1"
optional = true

[features]
default = ["woff2", "woff", "svg", "rayon"]
svg = ["dep:resvg", "dep:roxmltree"]
woff2 = ["dep:wuff", "wuff/brotli"]
woff = ["dep:wuff", "wuff/z"]
rayon = ["dep:rayon"]

[dev-dependencies]
criterion = "0.8"
serde_json = "1"


[[bench]]
name = "effects"
harness = false

[[bench]]
name = "gradient"
harness = false

[[bench]]
name = "fixtures"
harness = false

[[bench]]
name = "canvas"
harness = false

[[bench]]
name = "text"
harness = false
